[package]
name = "rust_playground"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

k256={version="0.12.0", features=["ecdh"]}
hex="0.4.3"
rand_core="0.6.3"
